apiVersion: v1
kind: Pod

metadata:
  name: postgres-pod
  namespace: database
  labels:
    app: postgres

spec:
  # nodeSelector를 지정하지 않아서 Kubernetes scheduler가 노드를 자율적으로 선택함
  containers:
    - name: postgres-container
      image: postgres:16-alpine
      env:
        - name: POSTGRES_USER
          value: practice
        - name: POSTGRES_PASSWORD
          value: practice-password
        - name: POSTGRES_DB
          value: practice_db
      ports:
        - containerPort: 5432
