# Argo CD에게 redis manifest 위치를 알려주는 자식 Application

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: redis-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/minmings111/k8s-practice.git
    targetRevision: main
    path: apps/redis

  destination:
    server: https://kubernetes.default.svc
    namespace: cache

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
