apiVersion: v1
kind: Pod

metadata:
  name: redis-pod
  namespace: cache
  labels:
    app: redis

spec:
  containers:
    - name: redis-container
      image: redis:7-alpine
      ports:
        - containerPort: 6379
